name: NovaCore
main: net.zeeraa.novacore.spigot.NovaCore
description: A core plugin
version: 1.0

softdepend: [Netherboard, HolographicDisplays, ProtocolLib]

permissions:
  novacore.gamelobby.forcemap:
    description: Allow force selecting maps
    default: op