name: NovaCore
main: net.zeeraa.novacore.spigot.NovaCore
description: A core plugin
version: 1.1
api-version: 1.13
softdepend: [Netherboard, HolographicDisplays, ProtocolLib, Citizens]

loadbefore: [NovaCoreGameEngine]